workflows:
  android-build:
    name: Android Debug Build
    max_build_duration: 60
    environment:
      java: 17
      android:
        image: android-34
    scripts:
      - name: Build debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
