
workflows:
  android-workflow:
    name: Android Debug Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      vars:
        GRADLE_OPTS: "-Xmx2048m"
      java: 23
      android:
        api_level: 34
        build_tools: 34.0.0
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your_email@example.com

    
